name: Test package on pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ./nestjs-graphql-utils
      - run: npm run build --if-present
        working-directory: ./nestjs-graphql-utils
      - run: npm test
        working-directory: ./nestjs-graphql-utils
